name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 30m

          script: |
            cd /home/ec2-user/Ueco-Entertainment

            git pull origin main

            npm install

            npm run build

            pm2 restart ueco || pm2 start npm --name "ueco" -- start

            pm2 save